### ISSUE TITLE
ERROR:root:**error** get_candles need reconnect

### ISSUE THREAD

**Issue by robin090** [dockerlead/iqoption-trading-server#4]
Start receiving stream from iqoption.com ...
ERROR:root:**error** get_candles need reconnect
ERROR:root:**error** get_candles need reconnect
ERROR:root:**error** get_candles need reconnect
ERROR:root:**error** get_candles need reconnect

**Comment by orendavisdev** [comment]
Can you be more specific for the reproduction step?

**Comment by robin090** [comment]
env.example
IQ_OPTION_USER=my mail
IQ_OPTION_PASSWORD=my password
APP_PORT=8000
WEB_CONCURRENCY=4

then run  python main.py

**Comment by orendavisdev** [comment]
can't reproduce
